### ISSUE TITLE
'Class auth does not exist' when saving some models

### ISSUE THREAD

**Issue by geoffbeaumont** [mpociot/versionable#20]
I have two models, both using versionable's VersionableTrait.

One model can be saved without a problem - the other can be saved from a front end component which updates it, but cannot be saved within the backend. The error I get is:

exception 'ReflectionException' with message 'Class auth does not exist' in <project-root>\vendor\laravel\framework\src\Illuminate\Container\Container.php:741

and looking back up the stack trace, this is triggered by the call to Auth::check() in VersionableTrait's getAuthUserId() method:

#5 <project-root>\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(120): Illuminate\Support\Facades\Facade::resolveFacadeInstance('auth')
#6 <project-root>\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(205): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 <project-root>\vendor\mpociot\versionable\src\Mpociot\Versionable\VersionableTrait.php(190): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#8 <project-root>\vendor\mpociot\versionable\src\Mpociot\Versionable\VersionableTrait.php(190): Illuminate\Support\Facades\Auth::check()
#9 <project-root>\vendor\mpociot\versionable\src\Mpociot\Versionable\VersionableTrait.php(157): qca\Applicants\Models\Assessment->getAuthUserId()
#10 <project-root>\vendor\mpociot\versionable\src\Mpociot\Versionable\VersionableTrait.php(79): qca\Applicants\Models\Assessment->versionablePostSave()

Obviously, removing the VersionableTrait from the model allows it to save correctly, but what's a whole lot more puzzling is that the other model works fine... Both models are fairly simple, and also very similar.

The controller involved doesn't seem to be important - before I implemented mk-conn's workaround from issue #11 I got the same error when saving both models (the second model has a relationship to this one), now it's not also trying to save a version for the first model the second saves fine.

I could understand if something was screwed up in my environment and Auth could _never_ be found - but I'm stumped as to how it can be found when saving a version for one model and not another!

Any ideas?

**Comment by geoffbeaumont** [comment]
Okay, I was wrong about what was going on here - the reason I was sometimes hitting this and not at others was because in some cases I wasn't changing any data, so Versionable wasn't trying to create a new version record. If it does, I get this error (front or back end).

So why do I have no Auth...

**Comment by geoffbeaumont** [comment]
Okay, so the issue here is that the application I'm running this in is based on OctoberCMS, which doesn't use the standard Laravel Auth system. It has a built in BackendAuth (deliberately named differently so you can still use the standard Auth for your front end system, and I'm using an OctoberCMS plugin called User which provides front end authentication and user management facilities - this does provide a facade named Auth, but it's a different class so the include in VersionableTrait is wrong for this (it also has a different interface - Auth::id() is not present).

The answer was to override the getAuthUserId() method in the classes I was using VersionableTrait in (has to be done in each class, as the trait would override a base class and traits can't be extended - the only other option would be to implement my own trait which would be a modified clone of VersionableTrait - but that would be more of a maintenance headache than cloning a single simple method into each class.

I can only record IDs from one of the authentication systems without modifying Versionable, but that's acceptable anyway for this system (in general it's enough to know that it was a back end user as there's no ID). If I do need to store both I'll have to store updated by IDs in the main record. Versionable can't possibly handle all scenarios out of the box!

I guess it might be possible to make the authentication system queried by Versionable configurable - not sure how many developers this would be useful for?
